package com.stefanini.model;
// Generated 07/11/2016 12:04:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Infracoes generated by hbm2java
 */
@Entity
@Table(name = "infracoes", catalog = "hackathon")
public class Infracoes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idInfracao", unique = true, nullable = false)
	private Integer idInfracao;
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="idAgente")
	private Agente idAgente;
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="idLocalInfracao")
	private Localinfracao idLocalInfracao;
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="idTipoInfracao")
	private Tipoinfracao idTipoInfracao;
	@ManyToOne(cascade=CascadeType.ALL)
	private Veiculos veiculo;
	

	@Column(name = "velocidade")
	private Integer velocidade;

	public Infracoes() {
	}

	public Infracoes(Agente idAgente, Localinfracao idLocalInfracao, Tipoinfracao idTipoInfracao, Veiculos veiculo) {
		this.idAgente = idAgente;
		this.idLocalInfracao = idLocalInfracao;
		this.idTipoInfracao = idTipoInfracao;
		this.veiculo= veiculo;
	}

	public Infracoes(Agente idAgente, Localinfracao idLocalInfracao, Tipoinfracao idTipoInfracao, Veiculos veiculo, Integer velocidade) {
		this.idAgente = idAgente;
		this.idLocalInfracao = idLocalInfracao;
		this.idTipoInfracao = idTipoInfracao;
		this.veiculo= veiculo;
		this.velocidade = velocidade;
	}

	
	public Integer getIdInfracao() {
		return this.idInfracao;
	}

	public void setIdInfracao(Integer idInfracao) {
		this.idInfracao = idInfracao;
	}

	//@Column(name = "idAgente", nullable = false)
	public Agente getIdAgente() {
		return this.idAgente;
	}

	public void setIdAgente(Agente idAgente) {
		this.idAgente = idAgente;
	}

	//@Column(name = "idLocalInfracao", nullable = false)
	public Localinfracao getIdLocalInfracao() {
		return this.idLocalInfracao;
	}

	public void setIdLocalInfracao(Localinfracao idLocalInfracao) {
		this.idLocalInfracao = idLocalInfracao;
	}

	//@Column(name = "idTipoInfracao", nullable = false)
	public Tipoinfracao getIdTipoInfracao() {
		return this.idTipoInfracao;
	}

	public void setIdTipoInfracao(Tipoinfracao idTipoInfracao) {
		this.idTipoInfracao = idTipoInfracao;
	}
	public Veiculos getVeiculo() {
		return veiculo;
	}

	public void setVeiculo(Veiculos veiculo) {
		this.veiculo = veiculo;
	}
	
	public Integer getVelocidade() {
		return this.velocidade;
	}

	public void setVelocidade(Integer velocidade) {
		this.velocidade = velocidade;
	}

}
